### ISSUE TITLE
是否有考虑支持vue3

### ISSUE THREAD

**Issue by allen-wIki** [lblblong/tarojs-router#3]

**Comment by lblblong** [comment]
暂时没有打算做 vue3 的支持
现有代码理论上是可以用在 vue3 上的，但是我没有试过

**Comment by doabit** [comment]
vue3 可以直接用，我用了

**Comment by allen-wIki** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lblblong/tarojs-router"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 晚上11:18
收件人:&nbsp;"lblblong/tarojs-router"<tarojs-router@noreply.github.com&gt;;
抄送:&nbsp;"765692772"<765692772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lblblong/tarojs-router] 是否有考虑支持vue3 (#3)





 
vue3 可以直接用，我用了
  



请问我使用了useRouter这个方法 会出现报错

react.development.js:1465 Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

1. You might have mismatching versions of React and the renderer (such as React DOM)

2. You might be breaking the Rules of Hooks

3. You might have more than one copy of React in the same app




请问你有遇到这个问题吗

**Comment by lblblong** [comment]
添加了 vue3 相关的支持，请使用 useRouterVue
